/* DoseCare V2 — calculator UI controller. */
(function () {
  'use strict';
  const $=id=>document.getElementById(id);
  const medicineSelect=$('medicine-select'), conditionField=$('condition-field'), conditionSelect=$('condition-select'), concentrationField=$('concentration-field'), concentrationSelect=$('concentration-select'), recommendedDose=$('recommended-dose'), form=$('dose-form'), message=$('form-message');
  const ageField=$('age-value')?.closest('.field'); const weightField=$('weight-value')?.closest('.field');
  const database=window.DoseCareV2Database; const medicines=database?database.getAll():[]; const byId=id=>database?.getById(id)||null;
  let frequencyField=null, frequencySelect=null;
  function toMg(amount,unit){const n=Number(amount);if(!Number.isFinite(n)||n<=0)return null;const u=String(unit||'mg').toLowerCase();if(['g','gram','grams'].includes(u))return n*1000;if(['mcg','µg','microgram','micrograms'].includes(u))return n/1000;return n;}
  function normalizeFormulation(f){
    if(!f)return null;
    if(f.volumeBased)return {...f,display:f.display||'Volume-based oral solution'};
    const c=f.concentration||{};
    let rawAmount=c.amount??f.amount??f.mgPer5mL??f.mgPerMl;
    let rawUnit=c.unit??f.unit??'mg';
    let volume=c.volume??f.volume??(f.mgPer5mL!==undefined?5:1);
    if((rawAmount===undefined||rawAmount===null)&&typeof f.display==='string'){
      const match=f.display.match(/([0-9.]+)\s*(mg|g|mcg)\s*\/\s*([0-9.]+)\s*mL/i);
      if(match){rawAmount=Number(match[1]);rawUnit=match[2];volume=Number(match[3]);}
    }
    const amountMg=toMg(rawAmount,rawUnit),volumeMl=Number(volume);
    if(amountMg===null||!Number.isFinite(volumeMl)||volumeMl<=0)return null;
    return {...f,mgPerMl:amountMg/volumeMl,display:f.display||`${rawAmount} ${rawUnit}/${volumeMl} mL`,concentration:{amount:amountMg,unit:'mg',volume:volumeMl,volumeUnit:'mL'}};
  }
  function doseText(r){if(r.type==='label_weight_age_based'||r.type==='label_age_based')return `${r.doseMin??r.minDose??r.dose}–${r.doseMax??r.maxDose??r.dose} ${r.doseUnit||r.unit||'mg/dose'}`;if(r.type==='volume_by_age')return `${r.minVolumeMl}–${r.maxVolumeMl} mL after each loose stool`;if(r.type==='volume_per_kg')return `75 mL/kg over ${r.durationHours} hours`;if(r.schedule?.length)return r.schedule.map(s=>`${s.dayRange}: ${s.doseMgPerKg??s.doseMgPerKgPerDose} mg/kg`).join(' • ');const a=r.minDose??r.dose??r.doseMgPerKg??r.doseMgPerKgPerDay,b=r.maxDose??r.dose??r.doseMgPerKg??r.doseMgPerKgPerDay;return `${a===b?a:`${a}–${b}`} ${r.unit||(r.type==='mg_per_kg_per_day'||r.type==='mg_per_kg_day'?'mg/kg/day':'mg/kg/dose')}`;}
  function requirements(r){if(!r)return {age:false,weight:false};const ageByBounds=r.minAgeWeeks!==undefined||r.maxAgeWeeks!==undefined||r.minAgeMonths!==undefined||r.maxAgeMonths!==undefined||r.minAgeYears!==undefined||r.maxAgeYears!==undefined;return {age:r.requiresAge??(ageByBounds||['age_based','label_age_based','label_weight_age_based','volume_by_age','volume_per_kg'].includes(r.type)),weight:r.requiresWeight??['mg_per_kg_per_day','mg_per_kg_day','mg_per_kg_per_dose','mg_per_kg_single_dose','weight_based','label_weight_age_based','volume_per_kg'].includes(r.type)};}
  function setFieldVisibility(r){const req=requirements(r);if(ageField)ageField.hidden=!req.age;if(weightField)weightField.hidden=!req.weight;if(!req.age)$('age-value').value='';if(!req.weight)$('weight-value').value='';}
  function ensureFrequencyField(){if(frequencyField)return;frequencyField=document.createElement('div');frequencyField.className='field';frequencyField.id='frequency-field';const label=document.createElement('label');label.htmlFor='frequency-select';label.textContent='Regimen / frequency';frequencySelect=document.createElement('select');frequencySelect.id='frequency-select';label.appendChild(frequencySelect);frequencyField.appendChild(label);conditionField.insertAdjacentElement('afterend',frequencyField);frequencyField.hidden=true;}
  function conditionGroups(rs){const map=new Map();rs.forEach(r=>{const key=r.condition||r.conditions?.[0]||r.id;if(!map.has(key))map.set(key,[]);map.get(key).push(r);});return [...map.entries()];}
  function ageInMonths(){const v=Number($('age-value')?.value),u=$('age-unit')?.value;if(!Number.isFinite(v)||v<0)return null;if(u==='years')return v*12;if(u==='weeks')return v/4.34524;return v;}
  function regimenMatchesAge(r){const m=ageInMonths();if(m===null)return false;let min=r.minAgeMonths,max=r.maxAgeMonths;if(r.minAgeYears!==undefined)min=Number(r.minAgeYears)*12;if(r.maxAgeYears!==undefined)max=Number(r.maxAgeYears)*12;if(min!==undefined&&m<Number(min))return false;if(max!==undefined&&m>Number(max))return false;return true;}
  function selectedRegimen(m){const rs=m?.regimens||[];if(rs.length===1)return rs[0];const group=conditionGroups(rs).find(([key])=>key===conditionSelect.value)?.[1]||[];if(!group.length)return null;const ageMatch=group.filter(regimenMatchesAge);if(ageMatch.length===1)return ageMatch[0];if(frequencySelect?.value){const chosen=group.find(r=>r.id===frequencySelect.value);if(chosen)return chosen;}return group[0];}
  function ageBandText(r){let min=r.minAgeMonths,max=r.maxAgeMonths;if(r.minAgeYears!==undefined)min=Number(r.minAgeYears)*12;if(r.maxAgeYears!==undefined)max=Number(r.maxAgeYears)*12;if(min===undefined&&max===undefined)return '';const fmt=n=>n%12===0?`${n/12} years`:`${n} months`;if(min!==undefined&&max!==undefined)return `${fmt(min)}–${fmt(max)}`;return min!==undefined?`≥ ${fmt(min)}`:`≤ ${fmt(max)}`;}
  function compatibleFormulations(m,r){const forms=m?.formulations||[];if(!r?.allowedFormulations?.length)return forms.map((f,i)=>({...f,__index:i}));const allowed=new Set(r.allowedFormulations.map(String));return forms.map((f,i)=>({...f,__index:i})).filter(f=>allowed.has(String(f.id)));}
  function renderConcentrations(m,r){concentrationSelect.innerHTML='';const forms=compatibleFormulations(m,r);forms.forEach(f=>{const o=document.createElement('option');o.value=String(f.__index);o.textContent=f.display||f.label||`${f.mgPer5mL} mg/5 mL`;concentrationSelect.appendChild(o);});concentrationField.hidden=forms.length<=1;if(!forms.length){concentrationField.hidden=false;const o=document.createElement('option');o.value='';o.textContent='No compatible formulation configured';concentrationSelect.appendChild(o);}}
  function render(){const m=byId(medicineSelect.value);conditionSelect.innerHTML='<option value="">Select condition / regimen</option>';concentrationSelect.innerHTML='';conditionField.hidden=true;concentrationField.hidden=true;ensureFrequencyField();frequencyField.hidden=true;frequencySelect.innerHTML='';if(!m){recommendedDose.textContent='Select a treatment first';setFieldVisibility(null);return;}const rs=m.regimens||[],groups=conditionGroups(rs);if(rs.length>1){conditionField.hidden=false;groups.forEach(([key])=>{const o=document.createElement('option');o.value=key;o.textContent=key;conditionSelect.appendChild(o);});recommendedDose.textContent='Select a condition / regimen to view the dose';setFieldVisibility(null);}else{const r=rs[0];recommendedDose.textContent=r?doseText(r):'Dose not configured';setFieldVisibility(r);renderConcentrations(m,r);return;}renderConcentrations(m,null);}
  function updateRegimenUI(){const m=byId(medicineSelect.value),rs=m?.regimens||[],group=conditionGroups(rs).find(([key])=>key===conditionSelect.value)?.[1]||[];if(group.length>1){frequencyField.hidden=false;frequencySelect.innerHTML='';group.forEach(r=>{const o=document.createElement('option');o.value=r.id;o.textContent=[ageBandText(r),r.frequencyText||r.id].filter(Boolean).join(' — ');frequencySelect.appendChild(o);});}else{frequencyField.hidden=true;frequencySelect.innerHTML='';}const r=selectedRegimen(m);if(r&&frequencySelect)frequencySelect.value=r.id;recommendedDose.textContent=r?doseText(r):'Select a condition / regimen to view the dose';setFieldVisibility(r);renderConcentrations(m,r);}
  medicines.forEach(m=>{const o=document.createElement('option');o.value=m.id;o.textContent=m.name;medicineSelect.appendChild(o);});medicineSelect.addEventListener('change',render);conditionSelect.addEventListener('change',updateRegimenUI);document.addEventListener('change',e=>{if(e.target===frequencySelect){const r=selectedRegimen(byId(medicineSelect.value));recommendedDose.textContent=r?doseText(r):'Select a condition / regimen to view the dose';setFieldVisibility(r);renderConcentrations(byId(medicineSelect.value),r);}});
  form.addEventListener('submit',e=>{e.preventDefault();message.textContent='';const m=byId(medicineSelect.value),r=selectedRegimen(m);if(!m||!r){message.textContent='Select a treatment and required condition.';return;}const req=requirements(r);const index=Math.max(0,Number(concentrationSelect.value)||0);const rawFormulation=(m.formulations||[])[index];const f=m.id==='ors'?rawFormulation:normalizeFormulation(rawFormulation);if(m.id!=='ors'&&!f){message.textContent='The selected oral-liquid formulation is not configured correctly.';return;}if(r.allowedFormulations?.length&&!r.allowedFormulations.map(String).includes(String(f?.id))){message.textContent='The selected formulation is not compatible with this regimen.';return;}let result;if(m.id==='ors'||r.type==='volume_by_age'||r.type==='volume_per_kg'){result=window.DoseCareORS?.calculate({medicine:m,regimen:r,weight:req.weight?$('weight-value').value:null,age:req.age?$('age-value').value:null,ageUnit:$('age-unit').value,formulation:f});if(!result){message.textContent='The ORS calculation engine is not available. Please refresh and try again.';return;}}else{result=window.DoseCareDosingEngine.calculate({medicine:m,regimen:r,weight:req.weight?$('weight-value').value:null,age:req.age?$('age-value').value:null,ageUnit:$('age-unit').value,formulation:f});}if(!result.ok){message.textContent=result.error;return;}const payload=JSON.stringify({medicine:m,formulation:f,...result});let saved=false;try{sessionStorage.setItem('dosecareV2Result',payload);saved=sessionStorage.getItem('dosecareV2Result')===payload;}catch(error){console.warn('DoseCare sessionStorage unavailable:',error);}if(!saved){try{localStorage.setItem('dosecareV2Result',payload);saved=localStorage.getItem('dosecareV2Result')===payload;}catch(error){console.warn('DoseCare localStorage unavailable:',error);}}if(!saved){message.textContent='The result could not be stored on this device. Please allow site storage and try again.';return;}window.location.assign('./result.html');});
  render();
})();