/* DoseCare V2 — bilingual UI controller. */
(function () {
  'use strict';
  const KEY='dosecareLanguage';
  const translations={
    'Calculation result':'نتيجة الحساب','Back to calculator':'العودة إلى الحاسبة','PATIENT INFORMATION':'معلومات المريض','Medicine':'الدواء','Condition / regimen':'الحالة / نظام الجرعة','Formulation':'الشكل والتركيز','Regimen':'نظام الجرعة','Age':'العمر','Weight':'الوزن','STEP-BY-STEP CALCULATION':'الحساب خطوة بخطوة','ADDITIONAL DETAILS':'تفاصيل إضافية','Active ingredient':'المادة الفعالة','Drug class':'الفئة الدوائية','Maximum daily dose':'الحد الأقصى للجرعة اليومية','Calculated daily dose':'الجرعة اليومية المحسوبة','Mechanism of action':'آلية العمل','Indications':'دواعي الاستعمال','Precautions & warnings':'الاحتياطات والتحذيرات','Adverse effects':'الآثار الجانبية','Interactions':'التداخلات الدوائية','Notes':'ملاحظات','SOURCES & REFERENCES':'المصادر والمراجع','No source record attached.':'لا يوجد مصدر مرفق.','No calculation found':'لم يتم العثور على عملية حساب','Return to the calculator and enter patient information.':'ارجع إلى الحاسبة وأدخل معلومات المريض.','BACK TO CALCULATOR':'العودة إلى الحاسبة','Result unavailable':'النتيجة غير متاحة','The calculation could not be read safely.':'تعذر قراءة نتيجة الحساب بشكل آمن','DOSE CALCULATOR':'حاسبة الجرعة','Select the medicine to begin.':'اختر الدواء للبدء.','Search medicine':'البحث عن الدواء','Type the first letters of a medicine…':'اكتب الأحرف الأولى من اسم الدواء…','Treatment':'الدواء','Select treatment':'اختر الدواء','Condition':'الحالة','Recommended pediatric dose':'جرعة الأطفال الموصى بها','Select a treatment first':'اختر الدواء أولًا','Weeks':'أسابيع','Months':'أشهر','Years':'سنوات','Oral-liquid concentration':'تركيز المستحضر الفموي السائل','CALCULATE DOSE':'احسب الجرعة'};
  const isWelcome=()=>!!document.querySelector('.welcome');
  function read(){try{const x=localStorage.getItem(KEY);if(x==='ar'||x==='en')return x}catch(_){}try{const x=sessionStorage.getItem(KEY);if(x==='ar'||x==='en')return x}catch(_){}return'en'}
  function save(lang){try{localStorage.setItem(KEY,lang)}catch(_){}try{sessionStorage.setItem(KEY,lang)}catch(_){} }
  function addSwitcher(){if(isWelcome())return;document.querySelectorAll('.topbar').forEach(t=>{if(t.querySelector('.language-switcher'))return;const w=document.createElement('div');w.className='language-switcher';w.innerHTML='<button type="button" data-lang="ar">عربي</button><span aria-hidden="true">|</span><button type="button" data-lang="en">EN</button>';t.appendChild(w)})}
  function translateText(root,lang){const walker=document.createTreeWalker(root||document.body,NodeFilter.SHOW_TEXT);while(walker.nextNode()){const n=walker.currentNode;if(!n.__dcEn)n.__dcEn=n.nodeValue;const original=n.__dcEn.trim();if(!original)continue;if(lang==='ar'&&translations[original])n.nodeValue=n.nodeValue.replace(original,translations[original]);else if(lang==='en')n.nodeValue=n.nodeValue.replace(n.nodeValue.trim(),original)}
    document.querySelectorAll('[placeholder]').forEach(el=>{if(!el.dataset.dcEnPlaceholder)el.dataset.dcEnPlaceholder=el.placeholder;el.placeholder=lang==='ar'?(el.id==='medicine-search'?'اكتب الأحرف الأولى من اسم الدواء…':el.dataset.dcEnPlaceholder):el.dataset.dcEnPlaceholder})}
  function setLanguage(lang,persist=true){lang=lang==='ar'?'ar':'en';document.documentElement.lang=lang;document.documentElement.dir=lang==='ar'?'rtl':'ltr';document.body.classList.toggle('arabic-ui',lang==='ar');if(persist)save(lang);translateText(document.body,lang);document.querySelectorAll('.language-switcher button').forEach(b=>{b.classList.toggle('active',b.dataset.lang===lang);b.setAttribute('aria-pressed',String(b.dataset.lang===lang))});window.dispatchEvent(new CustomEvent('dosecare:language-changed',{detail:{language:lang}}))}
  function init(){if(isWelcome())return;addSwitcher();document.addEventListener('click',e=>{const b=e.target.closest('.language-switcher button');if(b)setLanguage(b.dataset.lang,true)});setLanguage(read(),false);const observer=new MutationObserver(ms=>{const lang=read();ms.forEach(m=>m.addedNodes.forEach(node=>{if(node.nodeType===Node.ELEMENT_NODE)translateText(node,lang)})});observer.observe(document.body,{childList:true,subtree:true})}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();
